### ISSUE TITLE
Diagrama de secuencia

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-disttecpersis#1]
[diagrama de secuencia.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-secuencia-disttecpersis/files/7827768/diagrama.de.secuencia.pdf)

**Comment by Abraham890** [comment]
calificacion:28 puntos

**Comment by josealfredo79** [comment]
Debe haber un procedimiento Paso 1....Paso...2.....Paso 3...o en su defecto 1. 2...3.. en la practica

**Comment by josealfredo79** [comment]
Revisado
